project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "notes/*.qmd"

website:
  title: "Data Apothecary's Notes"
  
  navbar:
    background: "#bb5c54"
    foreground: white
    right:
      - href: notes.qmd
        text: Notes
      - icon: github
        href: https://github.com/chizapoth/data-apothecary-notes

  page-footer:
    center: "Made with [Quarto](https://quarto.org)"

format:
  html:
    theme: styles.scss
    toc: true
    code-overflow: wrap

filters:
  - webr
