project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "old_notes/*.qmd"
    - "!dev/**/*.qmd"
    - "!gc_mle/**/*.qmd"
    - "!random/**/*.qmd"

website:
  title: "Data Apothecary's Notes"
  description: "Notes on data science, causal inference, and clinical trials"
  
  navbar:
    background: "#bb5c54"
    foreground: white
    right:
      - href: notes.qmd
        text: Notes
      - href: about.qmd
        text: About
      - icon: github
        href: https://github.com/andreaczhang/data-apothecary-notes

  page-footer:
    center: "Made with [Quarto](https://quarto.org)"

format:
  html:
    theme: styles.scss
    toc: true
    code-overflow: wrap

filters:
  - webr
